services:
  - type: web
    name: menu-restaurant
    env: node
    buildCommand: cd backend && rm -f package-lock.json && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SECRET_KEY
        generateValue: true

